import { TotoRuntimeError, ValidationError } from "toto-api-controller";
import { TaskId } from "./TaskId";

/**
 * Models the data needed to send a task request TO an Agent (not to Gale Broker).
 * 
 * This is used by Gale Broker to send tasks to agents.
 */
export interface AgentTaskRequest {

    taskInstanceId: string; // Unique identifier for this specific execution of the task. This is generated by Gale Broker.
    taskInputData?: any;  // Input data needed for the task execution.
    parentTask?: ParentTask; // Optional parent task information for tracking task hierarchies.
}

export interface ParentTask {
    taskId: TaskId;         // Unique identifier of the parent task.   
    taskInstanceId: string; // Unique identifier for this specific execution of the parent task.
}

/**
 * Models the data returned from an Agent after executing a task.
 */
export class AgentTaskResponse {

    stopReason: "completed" | "failed" | "subtasks"; // Reason why the task execution stopped.
    taskOutput?: any;          // Output data produced by the task execution.

    subtasks?: SubTaskInfo[]; // Information about any subtasks that need to be executed as part of this task. This is used for tasks that decompose into multiple subtasks.

    constructor(stopReason: StopReason, taskOutput?: any, subtasks?: SubTaskInfo[]) {
        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.subtasks = subtasks;
    }

    static fromHTTPResponse(body: any): AgentTaskResponse {
        try {
            const parsed = JSON.parse(body);

            // Validate required fields
            if (!parsed.stopReason) throw new ValidationError(400, "Missing required field 'stopReason' in AgentTaskResponse.");

            return new AgentTaskResponse(parsed.stopReason, parsed.taskOutput, parsed.subtasks);

        } catch (error) {
            if (error instanceof SyntaxError) throw new TotoRuntimeError(500, `Failed to parse AgentTaskResponse from HTTP response body: ${body}`);
            throw error;
        }
    }
}

export interface SubTaskInfo {
    taskId: TaskId;             // Unique identifier of the subtask to be executed.
    taskInputData?: any;  // Input data needed for the subtask execution.
}

export type StopReason = "completed" | "failed" | "subtasks";