import { z } from "genkit";
import { TotoRuntimeError, ValidationError } from "totoms";

/**
 * Models the data needed to send a task request TO an Agent (not to Gale Broker).
 * 
 * This is used by Gale Broker to send tasks to agents.
 */
export class AgentTaskRequest<T extends z.ZodTypeAny> {

    correlationId?: string;                                     // Correlation ID to group related tasks together.
    command: Command;
    taskId: TaskId;                                             // Unique identifier of the task to be executed. E.g. "text.summarize"
    taskInstanceId?: string | null;                             // Unique identifier for this specific execution of the task. This is generated by Gale Broker.
    taskInputData?: StartTaskInputData | ResumeTaskInputData;   // Input data needed for the task execution.

    parentTask?: ParentTask;            // Optional parent task information for tracking task hierarchies.
    taskGroupId?: string;               // Optional group ID to group related subtasks together.
    branchId?: string;                  // Optional branch ID to group related subtasks together.

    constructor({ command, taskId, taskInputData, correlationId, taskInstanceId, parentTask, taskGroupId, branchId }: AgentTaskRequest<T>) {
        this.command = command;
        this.taskId = taskId;
        this.taskInputData = taskInputData;
        this.correlationId = correlationId;
        this.taskInstanceId = taskInstanceId;
        this.parentTask = parentTask;
        this.taskGroupId = taskGroupId;
        this.branchId = branchId;
    }

}

export interface ParentTask {
    taskId: TaskId;         // Unique identifier of the parent task.   
    taskInstanceId: string; // Unique identifier for this specific execution of the parent task.
}

export type StartTaskInputData = any; // Input data needed to start the task.
export interface ResumeTaskInputData {
    originalInput: any;         // Original input data passed when starting the task.
    childrenOutputs: any[];     // Outputs from child tasks.
}

/**
 * Models the data returned from an Agent after executing a task.
 */
export class AgentTaskResponse<T extends z.ZodTypeAny> {

    correlationId: string; // Correlation ID to group related tasks together.
    stopReason: StopReason; // Reason why the task execution stopped.
    taskOutput?: z.infer<T>;          // Output data produced by the task execution.

    constructor(stopReason: StopReason, correlationId: string, taskOutput?: z.infer<T>) {

        if (stopReason == 'subtasks') throw new ValidationError(400, "Only an OrchestratorAgent can return subtasks.");

        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.correlationId = correlationId;
    }

}

/**
 * Models the data returned from an Orchestrator Agent after executing a task.
 * Orchestrator agents can spawn subtasks.
 */
export class AgentTaskOrchestratorResponse<T extends z.ZodTypeAny> {

    correlationId: string;
    stopReason: StopReason;
    taskOutput?: z.infer<T>;
    subtasks?: TaskGroup[]; // Information about any subtasks that need to be executed as part of this task. This is used for tasks that decompose into multiple subtasks.

    constructor(stopReason: StopReason, correlationId: string, taskOutput?: z.infer<T>, subtasks?: TaskGroup[]) {
        this.correlationId = correlationId;
        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.subtasks = subtasks;

    }

}

export interface TaskGroup {
    groupId: string;            // Unique Id of the group.
    tasks: TaskInfo[];          // List of tasks in the group.
}

export interface TaskInfo {
    taskId: TaskId;             // Unique identifier of the subtask to be executed.
    taskInputData?: any;        // Input data needed for the subtask execution.
}

export type StopReason = "completed" | "failed" | "subtasks";

export type Command = StartCommand | ResumeCommand; 
export interface StartCommand {
    command: "start";
}
export interface ResumeCommand {
    command: "resume";
    completedTaskGroupId: string; // The ID of the group of subtasks that have been completed, triggering the resumption of the parent task.
    branchId?: string; // The ID of the branch within the task execution flow. In case of RESUME commands, this is mandatory
}

export type TaskId = string;