import { TotoRuntimeError, ValidationError } from "toto-api-controller";

/**
 * Models the data needed to send a task request TO an Agent (not to Gale Broker).
 * 
 * This is used by Gale Broker to send tasks to agents.
 */
export class AgentTaskRequest {

    taskId: TaskId;         // Unique identifier of the task to be executed. E.g. "text.summarize"
    taskInstanceId?: string; // Unique identifier for this specific execution of the task. This is generated by Gale Broker.
    taskInputData?: any;  // Input data needed for the task execution.
    correlationId?: string; // Correlation ID to group related tasks together.
    
    parentTask?: ParentTask; // Optional parent task information for tracking task hierarchies.

    constructor({taskId, taskInputData, correlationId, taskInstanceId, parentTask}: AgentTaskRequest) {
        this.taskId = taskId;
        this.taskInputData = taskInputData;
        this.correlationId = correlationId;
        this.taskInstanceId = taskInstanceId;
        this.parentTask = parentTask;
    }

    static fromHTTPRequest(req: any): AgentTaskRequest {

        // 1. Validate mandatory fields
        if (!req.body.taskId) throw new ValidationError(400, "Missing mandatory field: taskId");

        // 2. Extract fields
        return new AgentTaskRequest({
            taskId: req.body.taskId,
            taskInputData: req.body.taskInputData || null,
            correlationId: req.body.correlationId || null,
            taskInstanceId: req.body.taskInstanceId || null,
            parentTask: req.body.parentTask || null
        });
    }
}

export interface ParentTask {
    taskId: TaskId;         // Unique identifier of the parent task.   
    taskInstanceId: string; // Unique identifier for this specific execution of the parent task.
}

/**
 * Models the data returned from an Agent after executing a task.
 */
export class AgentTaskResponse {

    correlationId: string; // Correlation ID to group related tasks together.
    stopReason: "completed" | "failed" | "subtasks"; // Reason why the task execution stopped.
    taskOutput?: any;          // Output data produced by the task execution.

    subtasks?: SubTaskInfo[]; // Information about any subtasks that need to be executed as part of this task. This is used for tasks that decompose into multiple subtasks.

    constructor(stopReason: StopReason, correlationId: string, taskOutput?: any, subtasks?: SubTaskInfo[]) {
        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.subtasks = subtasks;
        this.correlationId = correlationId;
    }

    static fromHTTPResponse(body: any): AgentTaskResponse {
        try {
            const parsed = JSON.parse(body);

            // Validate required fields
            if (!parsed.stopReason) throw new ValidationError(400, "Missing required field 'stopReason' in AgentTaskResponse.");
            if (!parsed.correlationId) throw new ValidationError(400, "Missing required field 'correlationId' in AgentTaskResponse. An Agent always needs to return the correlation ID it received when triggered.");

            return new AgentTaskResponse(
                parsed.stopReason,
                parsed.correlationId,
                parsed.taskOutput,
                parsed.subtasks
            );

        } catch (error) {
            if (error instanceof SyntaxError) throw new TotoRuntimeError(500, `Failed to parse AgentTaskResponse from HTTP response body: ${body}`);
            throw error;
        }
    }
}

export interface SubTaskInfo {
    taskId: TaskId;             // Unique identifier of the subtask to be executed.
    taskInputData?: any;  // Input data needed for the subtask execution.
}

export type StopReason = "completed" | "failed" | "subtasks";

export type TaskId = string;