import { TotoRuntimeError, ValidationError } from "toto-api-controller";

/**
 * Models the data needed to send a task request TO an Agent (not to Gale Broker).
 * 
 * This is used by Gale Broker to send tasks to agents.
 */
export class OrchestratorAgentTaskRequest {

    command: Command;
    taskId: TaskId;         // Unique identifier of the task to be executed. E.g. "text.summarize"
    taskInstanceId?: string; // Unique identifier for this specific execution of the task. This is generated by Gale Broker.
    taskInputData?: any;  // Input data needed for the task execution.
    correlationId?: string; // Correlation ID to group related tasks together.
    
    parentTask?: ParentTask; // Optional parent task information for tracking task hierarchies.

    constructor({command, taskId, taskInputData, correlationId, taskInstanceId, parentTask}: OrchestratorAgentTaskRequest) {
        this.command = command;
        this.taskId = taskId;
        this.taskInputData = taskInputData;
        this.correlationId = correlationId;
        this.taskInstanceId = taskInstanceId;
        this.parentTask = parentTask;
    }

    static fromHTTPRequest(req: any): OrchestratorAgentTaskRequest {

        // 1. Validate mandatory fields
        if (!req.body.command) throw new ValidationError(400, "Missing mandatory field: command");
        if (!req.body.taskId) throw new ValidationError(400, "Missing mandatory field: taskId");

        // 2. Extract fields
        return new OrchestratorAgentTaskRequest({
            command: req.body.command,
            taskId: req.body.taskId,
            taskInputData: req.body.taskInputData || null,
            correlationId: req.body.correlationId || null,
            taskInstanceId: req.body.taskInstanceId || null,
            parentTask: req.body.parentTask || null
        });
    }
}

export interface ParentTask {
    taskId: TaskId;         // Unique identifier of the parent task.   
    taskInstanceId: string; // Unique identifier for this specific execution of the parent task.
}

/**
 * Models the data returned from an Agent after executing a task.
 */
export class OrchestratorAgentTaskResponse {

    correlationId: string; // Correlation ID to group related tasks together.
    stopReason: "completed" | "failed" | "subtasks"; // Reason why the task execution stopped.
    taskOutput?: any;          // Output data produced by the task execution.

    subtasks?: SubTaskInfo[]; // Information about any subtasks that need to be executed as part of this task. This is used for tasks that decompose into multiple subtasks.
    subtasksGroupId?: string; // Optional group ID to group related subtasks together. This is mandatory is subtasks are returned: it will allow Gale to tell the agent that spawned them when all subtasks are completed.

    constructor(stopReason: StopReason, correlationId: string, taskOutput?: any, subtasks?: SubTaskInfo[], subtasksGroupId?: string) {
        this.stopReason = stopReason;
        this.taskOutput = taskOutput;
        this.subtasks = subtasks;
        this.correlationId = correlationId;
        this.subtasksGroupId = subtasksGroupId;
    }

}

export interface SubTaskInfo {
    taskId: TaskId;             // Unique identifier of the subtask to be executed.
    taskInputData?: any;  // Input data needed for the subtask execution.
}

export type StopReason = "completed" | "failed" | "subtasks";

export type Command = StartCommand | ResumeCommand; 
export interface StartCommand {
    command: "start";
}
export interface ResumeCommand {
    command: "resume";
    completedSubtaskGroupId: string; // The ID of the group of subtasks that have been completed, triggering the resumption of the parent task.
}

export type TaskId = string;